
# ==========================
#   🔁 MIRROR TO GITHUB
# ==========================
mirror_to_github:
  stage: mirror
  image: alpine:latest
  before_script:
    - apk add --no-cache git
    - git config --global user.email "kaigrammm@gmail.com"
    - git config --global user.name "Mirror Bot"
  script:
    - git remote rm github || true
    - git remote add github https://${GITHUB_TOKEN}@github.com/websturing/Sewing-app-laravel.git
    - git fetch --all

    - git push --mirror github

    # push tags
    #- git push github --tags
  only:
    - branches
    - tags



