name: Laravel Post Deploy

on:
  workflow_dispatch: # Biar bisa dijalankan manual

jobs:
  post-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, xml, ctype, json, pdo_mysql

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Create .env file from secrets
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Generate APP_KEY
        run: php artisan key:generate

      - name: Run Migrations
        run: php artisan migrate --force

      - name: Cache Config
        run: php artisan config:cache
